### ISSUE TITLE
Custom dot files not installing

### ISSUE THREAD

**Issue by kuedan** [drewgrif/bookworm-scripts#4]
I just ran your install.sh script. Everything seemed to install, but the custome keybindings and wall papers are not installing.

**Comment by drewgrif** [comment]
If you installed the vanilla/non-customized versions it wouldn't.  Otherwise, it should.  Not sure why.  Could it be you installed on VM?

**Comment by kuedan** [comment]
I just installed it on a VM and it worked. My initial system was an x86 Macbook Air that it did not work. I am confused.

**Comment by drewgrif** [comment]
Needs to be debian/ubuntu
