### ISSUE TITLE
right-click on Openbox desktop generates popup error.

### ISSUE THREAD

**Issue by jfabernathy** [drewgrif/bookworm-scripts#5]
I installed the Openbox WM and a bunch more. I used the Just a Linux guy versions. On the desktop of openbox, if I right-click I get an error instead of the usual menu. I grabbed a screenshot of the message box.

The text is from notify-send:

Failed to execute command for pipe-menu "/home/drew/.local/bin/obmenu-generator......

Seems to be because I don't have a user drew.  My user is /home/jim

**Comment by jfabernathy** [comment]
/home/drew is hardcoded in menu.xml in .config/openbox

**Comment by drewgrif** [comment]
Just saw that and am making the change.  You beat me to it.  :+1:
